### PR TITLE
ref: new dsn for test org

### PR DESCRIPTION
**Pull request by bruno-garcia**
New test org for SDK development:

image

### CODE REVIEW

**Review by Tyrrrz — APPROVED** [review]
Looks good to me. Don't know if that's all the places that the DSN is used, but I'll trust you :)

Also, looking at `samples/Sentry.Samples.AspNetCore.Basic/Properties/launchSettings.json`, I would probably move environment variables to `appsettings.json`. I'm not sure if `launchSettings.json` is read by the IDE or by the framework, but `appsettings.json` seems like a better place for it. But it's my opinion and given that it's a sample, it probably doesn't matter.

**Comment by bruno-garcia** [comment]
@Tyrrrz In that particular example I wanted to show that environment variables are also supported. 
`dotnet run` and the IDEs supporting loading env vars from `launchSettings.json` hence the sample there.

I just did a string replace on the old dsn. I hope I didn't miss any :)

**Comment by bruno-garcia** [comment]
btw, There are other samples using `appsettings.json`

**Comment by Tyrrrz** [comment]
Makes sense.

**Pull request merged**
