### PR TITLE
ci: periodic dependency updates

### LINKED ISSUE #2141: Workflow to update dependencies automatically
We have several dependencies that need automatic update PR workflows added (i.e. dependency updater)

- Sentry CLI
- Sentry Cocoa SDK
- Sentry Java Android SDK

I believe we're getting Dependabot updates for most other things.

### PR DESCRIPTION
**Pull request by vaind**
closes #2141

TODO: someone with repo permissions needs to set a deploy key secret (cc @bruno-garcia ?)

### CODE REVIEW

**Comment by mattjohnsonpint** [comment]
For SentryCLI, we'll also need to update the hashes in Sentry.csproj.

**Comment by vaind** [comment]
> For SentryCLI, we'll also need to update the hashes in Sentry.csproj.

done

**Review by bruno-garcia — APPROVED** [review]

**Comment by bruno-garcia** [comment]
lets see if it works

**Comment by bruno-garcia** [comment]
https://github.com/getsentry/sentry-dotnet/actions/runs/4088597799

**Comment by mattjohnsonpint** [comment]
Thanks @vaind!!!

**Pull request merged**
