### PR TITLE
Refactor JSON serialization

### LINKED ISSUE #631: Refactor manual JSON serialization
- Generalize "don't write if value is null" into a single method
- Cleanup `JsonExtensions` into more meaningful methods
- ~~Make use of `EnumMember` attribute when serializing enums~~
- Use `JsonSerializer.Serializer` where it's more appropriate than `WriteDynamic` extension method
- ~~Potentially use `JsonConverter` instead of `IJsonSerializable`~~
- Type-check when deserializing `Dictionary<string, string>` (i.e. not nullable)

Related to #623

### PR DESCRIPTION
**Pull request by Tyrrrz**
Closes #631 
#skip-changelog

### CODE REVIEW

**Comment by Tyrrrz** [comment]
@bruno-garcia I think this is as far as it goes

**Comment by semuserable** [comment]
Can we make `JsonExtensions` public? We use some extensions in Unity. Copied them for now, but would be great if we just use the ones from Sentry .NET SDK.

cc @Tyrrrz @bruno-garcia

**Comment by Tyrrrz** [comment]
> Can we make `JsonExtensions` public? We use some extensions in Unity. Copied them for now, but would be great if we just use the ones from Sentry .NET SDK.
> 
> cc @Tyrrrz @bruno-garcia

@bruno-garcia You mentioned that you've reached some conclusion regarding this

**Comment by Tyrrrz** [comment]
@semuserable we had a discussion and decided to not make `JsonExtensions` public. The reason is that it will be too easy to accidentally add them in user code (because they will be visible in code completion drop down) and because that will introduce extra liability that we'd prefer to avoid. So for now copying is the safest approach.

Long term we may move these utility extensions along with some other stuff in a separate submodule that can be referenced in both the main SDK and Unity. /cc @bruno-garcia

**Comment by semuserable** [comment]
> @semuserable we had a discussion and decided to not make `JsonExtensions` public. The reason is that it will be too easy to accidentally add them in user code (because as extension methods they will always be visible in code completion drop down) and because that will introduce extra liability that we'd prefer to avoid. So for now copying is the safest approach.
> 
> Long term we may move these utility extensions along with some other stuff in a separate submodule that can be referenced in both the main SDK and Unity. /cc @bruno-garcia

Got you. Thanks for an update!

**Pull request merged**
