### PR TITLE
feat: Added ByteAttachmentContent

### PR DESCRIPTION
**Pull request by bitsandfoxes**
Adding a byte array as an attachment and then trying to send events can lead to `System.ObjectDisposedException: Cannot access a closed Stream.`

So instead of relying on one `stream` we create a `new MemoryStream` every time the stream gets requested.

The issue persists when trying to attach a stream.

### CODE REVIEW

**Comment by bruno-garcia** [comment]
> Running build.sh or build.ps1 should update the API changes on your local branch.

I wonder if it's worth adding a GHA that does the diff and commits to the branch

**Comment by SimonCropp** [comment]
> Running build.sh or build.ps1 should update the API changes on your local branch.

i disagree. the point of the api verification is to get people to view the changes and confirm they are correct. if we are going to automate the accepting of a new api, we may as well not have that step at all

**Comment by bruno-garcia** [comment]
@bitsandfoxes Today @SimonCropp shared with us that it's possible the verify files were nto written because the tests didn't run for that specific runtime. Do you have .NET Core 2.1 installed? It should run the tests on that target and create the file that @SimonCropp pushed to your branch: [`8756887` (#1384)](https://github.com/getsentry/sentry-dotnet/pull/1384/commits/8756887d18e029ae6a6fde111bfa856920c8070e)

**Comment by bitsandfoxes** [comment]
> @bitsandfoxes Today @SimonCropp shared with us that it's possible the verify files were nto written because the tests didn't run for that specific runtime. Do you have .NET Core 2.1 installed? It should run the tests on that target and create the file that @SimonCropp pushed to your branch: [`8756887` (#1384)](https://github.com/getsentry/sentry-dotnet/pull/1384/commits/8756887d18e029ae6a6fde111bfa856920c8070e)

I did not, but I do now. Thank for fixing my PR @bruno-garcia @SimonCropp

**Pull request merged**
