### PR TITLE
Rename Span.extras to Span.data

### PR DESCRIPTION
**Pull request by jamescrosswell**
Resolves https://github.com/getsentry/sentry-dotnet/issues/804

# On Hold

Putting this on pause. The current requirements we know of:
- Scope, event and transaction should have have an `Extra` property
- Span should have `Data`

However we've got an [RFC](https://github.com/getsentry/rfcs/pull/116/files) to flatten stuff on the span... so we're holding off on any changes here until that RFC goes through, at which point `Span.Extra` and `Span.Data` might disappear completely.

### CODE REVIEW

**Review by bitsandfoxes — CHANGES_REQUESTED** [review]
The `Scope` [needs to retain](https://docs.sentry.io/platforms/dotnet/enriching-events/context/#additional-data) `Extra`.

**Comment by jamescrosswell** [comment]
> The `Scope` [needs to retain](https://docs.sentry.io/platforms/dotnet/enriching-events/context/#additional-data) `Extra`.

Are you sure? Those docs say otherwise:
> Additional Data
> Additional Data is deprecated in favor of structured contexts.
>
> Sentry used to support adding unstructured "Additional Data" via SetExtra.

It looks like maybe we should be removing `Scope.Data` as well. I'm not sure what value having `SentryEvent.Extra` gives in that case since it would never come from the Scope, or a Transaction. 

More generally, I can do whatever, but we do need clarity on the actual requirements... which I'm not getting from the links on the [original issue](https://github.com/getsentry/sentry-dotnet/issues/804).

**Comment by bruno-garcia** [comment]
@jamescrosswell can we remove this branch?

**Comment by jamescrosswell** [comment]
> @jamescrosswell can we remove this branch?

Sure, seems unlikely we'd ever use it now... too hard to merge for too little gain.

**Pull request closed without merging**
