### PR TITLE
Add Order of execution tests

### PR DESCRIPTION
**Pull request by SimonCropp**
#skip-changelog

for several scenarios, records the order of execution of events, and the corresponding envelopes

### CODE REVIEW

**Comment by SimonCropp** [comment]
@mattjohnsonpint ok need a second pair of eyes. why is this only failing in ci?

**Comment by mattjohnsonpint** [comment]
Device tests will fail for Verify tests unless they are excluded with `[Trait("Category", "Verify")]`.  I need to find a more natural way to exclude them, but that's how it is presently.

For the others, I'm not sure - seems like sometimes you're getting events and sometimes you get none.  Maybe they're being sampled out when you don't expect them to be?  I'd have to debug further.

**Comment by SimonCropp** [comment]
@mattjohnsonpint are you happy to take over this one?

**Comment by mattjohnsonpint** [comment]
Yes

**Pull request closed without merging**
