### PR TITLE
fix: MAUI samples config - enable iOS/MAC deployment and debug for Windows

### PR DESCRIPTION
**Pull request by bricefriha**
As mentioned on Discord, I think it would be handy to allow Windows machines to deploy the iOS sample app using a paired Mac for testing purposes.

### Resources
in case you need some guidance to Pair a Mac to your Windows PC, Microsoft has some excellent [documentation for this](https://learn.microsoft.com/en-us/dotnet/maui/ios/pair-to-mac?view=net-maui-8.0)

#skip-changelog

### CODE REVIEW

**Comment by jamescrosswell** [comment]
@bricefriha would this then require people using the solution on Windows to have a paired Mac? We probably wouldn't want to do that as it would limit the number of people who could contribute to the repo... so it'd be good to "allow" people to work on Windows with a paired Mac but not "require" a paired Mac when working on Windows.

**Comment by bricefriha** [comment]
> so it'd be good to "allow" people to work on Windows with a paired Mac but not "require" a paired Mac when working on Windows

sorry for the confusion, you don't require to pair it to a mac with this config. The changes allows people to pair a mac but they don't have to.

e.g: I have a project with a similar configuration and I was able to work on it while in Germany away from my Mac

**Review by bruno-garcia — APPROVED** [review]
LGTM

**Comment by bruno-garcia** [comment]
Thanks. @jamescrosswell unless this breaks your workflow somehow, otherwise please merge

**Review by jamescrosswell — APPROVED** [review]

**Pull request merged**
