### PR TITLE
Add Environment to SentryOptions

### LINKED ISSUE #45: Setting the environment
I'm trying to setup the `ILogger` implementation in my project and I want to set the environment like I'm doing with the javascript client. On the `SentryOptions` class there's `Dsn` and `Release` properties but I'm not seeing anything for the `Environment`. How would this be set on the logger, or is it not implemented yet?

### PR DESCRIPTION
**Pull request by bruno-garcia**
* Read from environment variable
* Document Release field
Resolves #45

### CODE REVIEW

**Comment by xt0rted** [comment]
This should probably be added to `SentryAspNetCoreOptions` as well so it can be loaded from your `appsettings.json` or whatever other config providers are setup.

**Comment by bruno-garcia** [comment]
@xt0rted Now with Sentry's Environment support, it's advised to have a single DSN to for all your environments and let the event include which environment it was running in.

Wouldn't you say that if you are running 'Production' on your box, it'd load the prod configuration and essentially it is indeed production? Surely the affected user in case of error is you rather than a real user but unless you change your DB connection string, etc, to point to development, it's actually production.

I'm OK with setting the value also on the `SentryAspNetCoreOptions` with a `remark` that the value is automatically taken from `IHostingEnvironment` but it's possible to override if through that property.

We accepts PRs! :) I can guide your through the code if you want.

**Comment by xt0rted** [comment]
@bruno-garcia asp.net core has the concept of environments now, but you may need to switch out of development to see how something works such as with:
```c#
if (env.IsDevelopment())
{
    app.UseBrowserLink();
    app.UseDeveloperExceptionPage();
}
else
{
    app.UseExceptionHandler("/Home/Error");
}
```
If I'm doing that locally to test how something works that's not a true production environment and I wouldn't want any data being associated with it. Slack or PagerDuty notifications shouldn't trigger because I was debugging something.

I just added this property onto `SentryAspNetCoreOptions` and using it like so:
```diff
index e299586..5fb7dae 100644
--- a/src/Sentry.AspNetCore/SentryMiddleware.cs
+++ b/src/Sentry.AspNetCore/SentryMiddleware.cs
 internal void PopulateScope(HttpContext context, Scope scope)
 {
     scope.Sdk.Name = NameAndVersion.Name;
     scope.Sdk.Version = NameAndVersion.Version;
 
     if (_hostingEnvironment != null)
     {
         scope.Environment = _hostingEnvironment.EnvironmentName;
         scope.SetWebRoot(_hostingEnvironment.WebRootPath);
     }
 
     // TODO: Find route template (MVC integration)
     // TODO: optionally get transaction from request through a dependency
     //scope.Transaction = context.Request.PathBase;
 
     scope.Populate(context);
 
     if (_options?.IncludeActivityData == true)
     {
         scope.Populate(Activity.Current);
     }
+
+    if (!string.IsNullOrEmpty(_options?.Environment))
+    {
+        scope.Environment = _options.Environment;
+    }
 }
```

That lets it auto populate from the hosting environment, but any value in `Sentry:Environment` will override it. If that's a good approach I can send a PR in for this once I add some tests in.

**Comment by xt0rted** [comment]
Forgot to mention that if I set it like this it doesn't work because the hosting environment overwrites it.

```diff
 public static IWebHostBuilder UseSentry(
     this IWebHostBuilder builder,
     Action<SentryAspNetCoreOptions> configureOptions)
 {
     var aspnetOptions = new SentryAspNetCoreOptions();
 
     // Default aspnetOptions to sentryOptions configuration:
     aspnetOptions.ConfigureOptionsActions.Add(o =>
     {
         if (!string.IsNullOrWhiteSpace(aspnetOptions.Dsn))
         {
             o.Dsn = new Dsn(aspnetOptions.Dsn);
         }
 
         o.Release = aspnetOptions.Release;
+        o.Environment = aspnetOptions.Environment;
     });
 
     builder.ConfigureLogging((context, logging) =>
     {
         context.Configuration.GetSection("Sentry").Bind(aspnetOptions);
         configureOptions?.Invoke(aspnetOptions);
 
         logging.AddFilter<SentryLoggerProvider>(
             "Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware",
             LogLevel.None);
 
         logging.AddSentry(o => aspnetOptions.Apply(o));
     });
 
     builder.ConfigureServices(c =>
     {
         c.AddSingleton(aspnetOptions);
         c.AddTransient<IStartupFilter, SentryStartupFilter>();
 
         c.AddSentry();
     });
 
     return builder;
 }
```

**Comment by bruno-garcia** [comment]
I'm not sure I followed your last point.
Do you mind joining: https://gitter.im/getsentry/dotnet ?

Your change seem to be the way to go. It's pretty much the same as `Release`.
If you follow the usages of `Release` on `SentryAspNetCoreOptions` and `SentryOptions` you'll see what i mean.

Easier if we can discuss it on gitter?

**Pull request merged**
