### PR TITLE
DisabledHub.StartTransaction now returns NoOpTransaction

### LINKED ISSUE #829: DisabledTransaction or DisabledSpan if SDK is disabled, eg empty DSN
Right now the .NET SDK is allocating on every performance API call even if the SDK is non-functional (aka disabled), ideally, we'd do the NoOp pattern as we do on Java.

This SDK already does the NoOp pattern (eg Disabled) for many things, not yet for the performance API.

https://github.com/getsentry/sentry-dotnet/blob/37eb4a54cee682bec0d63435ce9959a67fb4656e/src/Sentry/Extensibility/DisabledHub.cs#L47-L54

Originally conflicted with #747 however we now have `NoOpSpan` and `NoOpTransaction` classes available.

@brustolin we'd need on Cocoa too.
@untitaker Python also does not do it, was there a reason or just because it's not a common thing in the Python ecosystem?
@bruno-garcia wanted to confirm that before going ahead and doing the changes.

### PR DESCRIPTION
**Pull request by jamescrosswell**
Resolves #829 

Replaces https://github.com/getsentry/sentry-dotnet/pull/3574 (cherry picked commits to target `main` branch instead of the `version-5.0.0` branch.

### CODE REVIEW

**Review by bitsandfoxes — APPROVED** [review]

**Comment by bitsandfoxes** [comment]
macOS is not happy today

**Comment by jamescrosswell** [comment]
> macOS is not happy today

Yeah I'm not even seeing any errors in the logs. It runs `dotnet restore` and then just stops logging after a while.
- We can't turn on diagnostic logging either, since then we run out of disk space 😢 
- We can't even upgrade to a larger runner since the [larger macOs runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/about-larger-runners#specifications-for-general-larger-runners) just come with more memory (not more disk space) 😭 

That leaves us in a bit of a pickle.

**Review by bitsandfoxes — APPROVED** [review]
LGTM!

**Comment by Joshhua5** [comment]
Can we expand on this and use the NoOpTransaction based on a sampling rate at the start of a transaction and not the end? 
Sentry is close to half of all our memory allocations and reducing the sample rate isn't effective at reducing that.

**Comment by bitsandfoxes** [comment]
> Can we expand on this and use the NoOpTransaction based on a sampling rate at the start of a transaction and not the end?

That's a very fair request that I put in https://github.com/getsentry/sentry-dotnet/issues/3636. We're moving towards something of a spans-only world but maybe we can sneak this in somewhere in between to make life easier?

**Pull request merged**
