### PR TITLE
Serialize arbitrary objects in contexts

### LINKED ISSUE #822: Custom Context object serialized as string
Adding an object to be serialized like:

```csharp
if (uname is { })
{
    s.Contexts["uname"] = new
    {
        uname.Machine,
        uname.Nodename,
        uname.Release,
        uname.Sysname,
        uname.Version
    };
}
```

Results in a broken contexts:

image

### PR DESCRIPTION
**Pull request by Tyrrrz**
Fixes #822

### CODE REVIEW

**Review by bruno-garcia — COMMENTED** [review]
I was thinking this would be hard for some reason, this is great stuff!!

**Comment by bruno-garcia** [comment]
If we merge this today I'll make a release and use it

**Comment by Tyrrrz** [comment]
I really need to refactor the JSON stuff somehow. I've been putting it off for very long, it's quite ugly at the moment.

**Comment by bruno-garcia** [comment]
> I really need to refactor the JSON stuff somehow. I've been putting it off for very long, it's quite ugly at the moment.

Is there a tracking issue for that already?

**Review by bruno-garcia — APPROVED** [review]

**Comment by Tyrrrz** [comment]
Yea: #631

**Pull request merged**
