### PR TITLE
show an example of snapshot testing using Verify

### PR DESCRIPTION
**Pull request by SimonCropp**
https://github.com/VerifyTests/Verify

### CODE REVIEW

**Comment by bruno-garcia** [comment]
Nice snapshot library @SimonCropp.
I'll keep this open until I get some time to proper consider this.
I'd love to get this in and will probably do so when I get time to lift the dep to the test/Directory.Build.props and use it in other tests asserting all of the object's state.

**Comment by SimonCropp** [comment]
I did a purge of forked repos. hence this was closed. let me know if u want it resubmitted. or u want to get on a call to discuss

**Comment by bruno-garcia** [comment]
Thanks @SimonCropp.
I think the example in the PR is a great starting point for us.

**Pull request closed without merging**
