### PR TITLE
Sample Blazor Wasm

### PR DESCRIPTION
**Pull request by bruno-garcia**
image

### CODE REVIEW

**Comment by bruno-garcia** [comment]
Fails on Windows only, odd

**Review by Tyrrrz — APPROVED** [review]

**Comment by Tyrrrz** [comment]
No changes required after all?

**Comment by Tyrrrz** [comment]
No idea what fails the build

**Comment by DominikPf** [comment]
@bruno-garcia Hi, i just tried to run your sample project.
But unfortunately it doesn't report the Events to Sentry.
The unhandled Exception ist displayed in the Browser Console. (Blazor Default)
But no Network request is sent.

If i try to send a Message manually it works (SentrySdk.CaptureMessage)

Is additional configuration needed?

Tested with Sentry (2.1.8, 3.0.0-alpha.5 & your codebase from branch "sample/blazor-wasm")

**Comment by bruno-garcia** [comment]
@DominikPf what browser did you tried? I'm afraid Threads in Wasm is still not generally supported

**Comment by bruno-garcia** [comment]
@DominikPf I just tested it (bumped to net5.0) and it worked: https://twitter.com/brungarc/status/1331056131624591362

The MEL integration isnt' capturing breadcrumbs, so can be improved though

**Comment by DominikPf** [comment]
@bruno-garcia The updated Version with net5 works like a charm. 
Thank you 👍

**Comment by bruno-garcia** [comment]
@DominikPf curious about your experience with it. Let us know how it goes. Thanks

**Pull request merged**
