### PR TITLE
lock file for nuget

### PR DESCRIPTION
**Pull request by bruno-garcia**
A year and a half later: #247

### CODE REVIEW

**Comment by bruno-garcia** [comment]
image
always on Windows it break, why

**Comment by bruno-garcia** [comment]
Still unanswered: https://stackoverflow.com/questions/57161512/nuget-lock-file-fails-to-restore-with-locked-mode

**Comment by Tyrrrz** [comment]
What are we trying to achieve with this?

**Comment by bruno-garcia** [comment]
@Tyrrrz lock the version of transitive dependencies so we always restore everything at the same version

**Comment by Tyrrrz** [comment]
@bruno-garcia is the current behavior causing issues? Just curious because I've never had any issues that would be solved by a NuGet lock file.

**Comment by bruno-garcia** [comment]
@Tyrrrz Not raising this as a reaction to a bug. Just want to guarantee reproducible builds to avoid any potential issues that arise from dependencies releasing new versions and further builds changing the dependency dependency tree. 

Some downsides to this I'm no aware of?

**Comment by Tyrrrz** [comment]
> Some downsides to this I'm no aware of?

Well, committing a huge file to VCS for one ;)

**Comment by bruno-garcia** [comment]
@Tyrrrz I thought you loved nodejs

**Comment by Tyrrrz** [comment]
@bruno-garcia Not necessarily. NPM lockfiles need to be committed (which I absolutely hate) because NPM package resolution strategy is rather permissive when it comes to different versions (by default it's latest minor). That said, even if you run `npm ci` instead of `npm i`, it will always resolve to the exact versions found in `package.json`.

NuGet, on the other hand, never had that retarded design decision in the first place, so it's safe from such issues. 🙂 Thus, I don't really see a point in lockfiles here.

**Pull request closed without merging**
