### PR TITLE
Adjust paramer type in AddBreadcrumb

### PR DESCRIPTION
**Pull request by jairbubbles**
Always better to use a concrete type, also it's now consistent with the other extension method.

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Looks good @jairbubbles.
Can you please add a quick changelog entry? Should be something like this (in `## Unreleased` section):

```
- Adjust paramer type in `AddBreadcrumb` to use `IReadOnlyDictionary<...>` instead of `Dictionary<...>` [#1000](https://github.com/getsentry/sentry-dotnet/pull/1000)
```

**Comment by jairbubbles** [comment]
@Tyrrrz  Done!

**Comment by Tyrrrz** [comment]
Thanks!

**Comment by bruno-garcia** [comment]
Thanks @jairbubbles !

**Pull request merged**
