### PR TITLE
move to target typed new

### PR DESCRIPTION
**Pull request by SimonCropp**
#skip-changelog

### CODE REVIEW

**Comment by mattjohnsonpint** [comment]
This seems like overkill.  I'm fine with using targeted type new - *when evident*

image

But some of these cases seem like they types are not evident, such as the first ones in the review:

```diff
-        _backgroundWorker = new BackgroundWorker(new FakeTransport(), new SentryOptions { MaxQueueItems = 1000 });
-        _event = new SentryEvent();
+        _backgroundWorker = new BackgroundWorker(new FakeTransport(), new() { MaxQueueItems = 1000 });
+        _event = new();
```

**Comment by SimonCropp** [comment]
fair enough. will close this one and re-do

**Comment by mattjohnsonpint** [comment]
Please don't spend too much time on this.  It's fine if it's automated, but no need to scrub everything.

**Comment by SimonCropp** [comment]
ok

**Pull request closed without merging**
