### PR TITLE
Add GitHub Action to ensure changelog was modified

### PR DESCRIPTION
**Pull request by Tyrrrz**

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Little demo:

**Contains changelog**

image

**Does not contain changelog**

image

(GitHub UI is ugly for some reason)

**Review by bruno-garcia — APPROVED** [review]
🥇

**Comment by bruno-garcia** [comment]
Gotta add a changelog now to test this :D

**Comment by bruno-garcia** [comment]
I guess I believe ur screenshots

**Pull request merged**
