### PR TITLE
fallback to request path for route

### PR DESCRIPTION
**Pull request by SimonCropp**
potential fix for #1835

### CODE REVIEW

**Comment by SimonCropp** [comment]
@mattjohnsonpint @bruno-garcia @lucas-zimerman thoughts on this as a solution for pre-flight requests?

**Review by bruno-garcia — CHANGES_REQUESTED** [review]
Pleas don't use the raw URL unless the new "source: raw" is provided. Transactions are grouped by name and raw URL can cause issues

**Comment by lucas-zimerman** [comment]
I think this is more of a business rule on what todo with pre-flight requests? Sentry UI should mention it's a pre-flight request so users don't get confused with requests with the `wrong` method  succeeding.

What if we just don't create a new transaction for pre-flight requests? I see them just as a transaction quota burner than giving any important info to the end user.

**Comment by mattjohnsonpint** [comment]
> Pleas don't use the raw URL unless the new "source: raw" is provided. Transactions are grouped by name and raw URL can cause issues

I think @bruno-garcia is referring to https://develop.sentry.dev/sdk/event-payloads/transaction/#transaction-annotations

```json
{
  "transaction_info": {
    "source": "url"
  }
}
```

**Comment by mattjohnsonpint** [comment]
> I think this is more of a business rule on what todo with pre-flight requests? Sentry UI should mention it's a pre-flight request so users will get confused with requests with the `wrong` method succeeding.
> 
> What if we just don't create a new transaction for pre-flight requests? I see them just as a transaction quota burner than giving any important info to the end user.

@lucas-zimerman - Preflight requests are indeed HTTP requests that get made from the client to the server.  It's possible they could be a source of slowness, depending on how the server is configured to handle them.  I think we should not filter them out.

**Comment by mattjohnsonpint** [comment]
Per internal discussion, we've decided that OPTIONS requests do not need to be sent to Sentry after all.

**Pull request closed without merging**
