### PR TITLE
feat: Added `instruction_addr_adjustment` attribute

### PR DESCRIPTION
**Pull request by bitsandfoxes**
Based on https://github.com/getsentry/rfcs/pull/43

### CODE REVIEW

**Comment by mattjohnsonpint** [comment]
From reading the RFC and looking at the Relay implementation, I think this is supposed to go on `SentryStackTrace`, not on `SentryStackFrame`.

**Comment by mattjohnsonpint** [comment]
The per-frame field is the `adjust_instruction_addr` boolean mentioned later in the RFC that *Symbolicator* adds.

**Review by bruno-garcia — APPROVED** [review]

**Review by mattjohnsonpint — CHANGES_REQUESTED** [review]
hold momentarily...

**Review by mattjohnsonpint — APPROVED** [review]

**Comment by mattjohnsonpint** [comment]
Thanks @bitsandfoxes ! 🎉

**Pull request merged**
