### PR TITLE
Dont unsubscribe from AppDomain.UnobservedTaskException on dispose

### LINKED ISSUE #321: on async Main, unhandled exception unregisters before capturing crash
```csharp
static void Main(string[] args)
{
    using var _ = SentrySdk.Init();
    throw null;
}
```

This exception is captured as expected by the unhandled exception handler.

```csharp
static async Task Main(string[] args)
{
    using var _ = SentrySdk.Init();
    throw null;
}
```

The code above doesn't work as expected. Before calling the `UnhandledException` handler the SDK goes out of the `using` "block" and unregisters the unhandled exception integration.

### PR DESCRIPTION
**Pull request by SimonCropp**
fixes #321

### CODE REVIEW

**Review by bruno-garcia — COMMENTED** [review]
Are calling Unregister on integrations when the Hub is disposed? I wonder if that could be an alternative approach.
Integrations can still unregister (even though we wouldn't be using that from SentrySdk.Close -> Hub.Dispose

Thoughts?

**Comment by SimonCropp** [comment]
no objections here. should i close this?

@bruno-garcia can u show us what u mean via a PR

**Comment by mattjohnsonpint** [comment]
@bruno-garcia writes code? 😄

**Comment by lucas-zimerman** [comment]
Could we add the `Unregister` to `ISdkIntegration ` instead of `IInternalSdkIntegration`?

**Comment by mattjohnsonpint** [comment]
After some discussion, it seems to makes sense to kill `Unregister` completely, as long as we don't break integrations.

**Comment by mattjohnsonpint** [comment]
Done in #1656

**Pull request closed without merging**
