### PR TITLE
ignore null context values

### PR DESCRIPTION
**Pull request by SimonCropp**
fix for https://github.com/getsentry/sentry-dotnet/issues/1332

### CODE REVIEW

**Comment by mattjohnsonpint** [comment]
Please also add a test that ensure the length header of the envelope comes out correctly, since that was the issue originally reported.  Thanks.

**Comment by SimonCropp** [comment]
@mattjohnsonpint 

> Please also add a test that ensures the length header of the envelope comes out correctly, since that was the issue originally reported. Thanks.

done

**Comment by mattjohnsonpint** [comment]
Test is failing

**Comment by SimonCropp** [comment]
test fixed

**Review by mattjohnsonpint — APPROVED** [review]

**Pull request merged**
