### PR TITLE
ci: Add Default Platform Label to PRs and Issues

### PR DESCRIPTION
**Pull request by philipphofmann**
#skip-changelog

### CODE REVIEW

**Comment by lucas-zimerman** [comment]
```
RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/andymckay/labeler/e6c4322d0397f3240f0e7e30a33b5c5df2d39e90/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async label (/home/runner/work/_actions/andymckay/labeler/e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
```
Action run shown an error, is it because the PR isn't merged?

**Review by bruno-garcia — APPROVED** [review]

**Comment by SimonCropp** [comment]
what value is a label added to all issues?

**Comment by philipphofmann** [comment]
> what value is a label added to all issues?

So we can use it on our team mobile board on GitHub for filtering for .NET issues across repositories as this one here, Unity and also docs.

**Comment by philipphofmann** [comment]
I forgot to add, that we currently can't filter by repo or label, because this https://github.com/orgs/getsentry/projects/19 is still in beta.

**Pull request merged**
