### PR TITLE
Add Sentry to global usings

### LINKED ISSUE #1163: Add `Sentry` to global usings
If `ImplicitUsings` is set to true, add `Sentry` as a global using via msbuild:

See: https://github.com/spectreconsole/spectre.console/pull/516/files

### PR DESCRIPTION
**Pull request by SimonCropp**
fixes #1163

 * [x] Add docs about opting in to implicit usings and how to resolve conflicts. consider add a pointer to feature here https://docs.sentry.io/platforms/dotnet/  https://github.com/getsentry/sentry-docs/pull/4585

### CODE REVIEW

**Comment by lucas-zimerman** [comment]
Is it possible to add some tests for it?

**Review by bruno-garcia — COMMENTED** [review]
❤️ 

Do we need a major bump here and docs to help users opt-out if they have conflicts?

More importantly: Isn't this going to immediately break anyone using `Span<T>`?

**Comment by SimonCropp** [comment]
does span need to be public?

**Review by bruno-garcia — APPROVED** [review]

**Review by lucas-zimerman — APPROVED** [review]

**Comment by bruno-garcia** [comment]
@SimonCropp feel free to merge this once we have some docs to go with it. 
I also propose causing a conflict on purpose to get an error message and throw it in the Troubleshooting page: https://docs.sentry.io/platforms/dotnet/troubleshooting/ There we can point out how users can't opt-out of this or how to resolve the conflict. If that would be beneficial.

**Pull request merged**
