### PR TITLE
test: sentry tests android net6

### PR DESCRIPTION
**Pull request by bruno-garcia**
Commented out tests that crash the runner on Android. This will serve to help debug later why they can't run.

Seems like `Task.Yield`, `Task.Run` `new HttpClient().Get` and others are not supported.

The MAUI project is not necessary to run `Sentry.Tests` on an Android device. This branch was a fork of getting net6 to work

All tests run but some fail:

```
2021-05-01 16:26:06.508 2937-2995/io.sentry.samples.android I/DOTNET: 47) 	[FAIL] Sentry.Tests.TaskUnobservedTaskExceptionIntegrationTests.Register_UnhandledException_Subscribes   Test name: Sentry.Tests.TaskUnobservedTaskExceptionIntegrationTests.Register_UnhandledException_Subscribes
       Assembly:  [Sentry.Tests, Version=3.
2021-05-01 16:26:06.508 2937-2995/io.sentry.samples.android I/DOTNET: 3.1.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0]
       Exception messages: System.NotImplementedException : The method or operation is not implemented.   Exception stack traces:    at System.RuntimeType.MakeGenericType(Type[] instantiation)
       at Cast
2021-05-01 16:26:06.508 2937-2995/io.sentry.samples.android I/DOTNET: le.DynamicProxy.Generators.MethodWithInvocationGenerator.BuildProxiedMethodBody(MethodEmitter emitter, ClassEmitter class, ProxyGenerationOptions options, INamingScope namingScope)
       at Castle.DynamicProxy.Generators.MethodGenerator.Generate(ClassEmitter 
2021-05-01 16:26:06.508 2937-2995/io.sentry.samples.android I/DOTNET: class, ProxyGenerationOptions options, INamingScope namingScope)
        at Castle.DynamicProxy.Contributors.CompositeTypeContributor.ImplementMethod(MetaMethod method, ClassEmitter class, ProxyGenerationOptions options, OverrideMethodDelegate overrideMethod)
     
2021-05-01 16:26:06.508 2937-2995/io.sentry.samples.android I/DOTNET:     at Castle.DynamicProxy.Contributors.CompositeTypeContributor.Generate(ClassEmitter class, ProxyGenerationOptions options)
        at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateType(String name, Type[] interfaces, INamingScope namingScope)
       a
2021-05-01 16:26:06.508 2937-2995/io.sentry.samples.android I/DOTNET: t Castle.DynamicProxy.Generators.ClassProxyGenerator.<>c__DisplayClass1_0.<GenerateCode>b__0(String n, INamingScope s)
        at Castle.DynamicProxy.Generators.BaseProxyGenerator.<>c__DisplayClass33_0.<ObtainProxyType>b__0(CacheKey _)
       at Castle.Core.Interna
2021-05-01 16:26:06.508 2937-2995/io.sentry.samples.android I/DOTNET: l.SynchronizedDictionary`2[[Castle.DynamicProxy.Generators.CacheKey, Castle.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc],[System.Type, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].G
2021-05-01 16:26:06.520 2937-2995/io.sentry.samples.android I/DOTNET: 49) 	[FAIL] Sentry.Tests.TaskUnobservedTaskExceptionIntegrationTests.Handle_WithException_CaptureEvent   Test name: Sentry.Tests.TaskUnobservedTaskExceptionIntegrationTests.Handle_WithException_CaptureEvent
       Assembly:  [Sentry.Tests, Version=3.3.1.0, Cul
2021-05-01 16:26:06.520 2937-2995/io.sentry.samples.android I/DOTNET: ture=neutral, PublicKeyToken=fba2ec45388e2af0]
       Exception messages: System.NotImplementedException : The method or operation is not implemented.   Exception stack traces:    at System.RuntimeType.MakeGenericType(Type[] instantiation)
       at Castle.Dynamic
2021-05-01 16:26:06.520 2937-2995/io.sentry.samples.android I/DOTNET: Proxy.Generators.MethodWithInvocationGenerator.BuildProxiedMethodBody(MethodEmitter emitter, ClassEmitter class, ProxyGenerationOptions options, INamingScope namingScope)
       at Castle.DynamicProxy.Generators.MethodGenerator.Generate(ClassEmitter class, Pro
2021-05-01 16:26:06.520 2937-2995/io.sentry.samples.android I/DOTNET: xyGenerationOptions options, INamingScope namingScope)
        at Castle.DynamicProxy.Contributors.CompositeTypeContributor.ImplementMethod(MetaMethod method, ClassEmitter class, ProxyGenerationOptions options, OverrideMethodDelegate overrideMethod)
       at Castl
2021-05-01 16:26:06.520 2937-2995/io.sentry.samples.android I/DOTNET: e.DynamicProxy.Contributors.CompositeTypeContributor.Generate(ClassEmitter class, ProxyGenerationOptions options)
        at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateType(String name, Type[] interfaces, INamingScope namingScope)
       at Castle.D
2021-05-01 16:26:06.520 2937-2995/io.sentry.samples.android I/DOTNET: ynamicProxy.Generators.ClassProxyGenerator.<>c__DisplayClass1_0.<GenerateCode>b__0(String n, INamingScope s)
        at Castle.DynamicProxy.Generators.BaseProxyGenerator.<>c__DisplayClass33_0.<ObtainProxyType>b__0(CacheKey _)
       at Castle.Core.Internal.Synchron
2021-05-01 16:26:06.520 2937-2995/io.sentry.samples.android I/DOTNET: izedDictionary`2[[Castle.DynamicProxy.Generators.CacheKey, Castle.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc],[System.Type, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Ca
2021-05-01 16:26:06.520 2937-2995/io.sentry.samples.android I/DOTNET: cheKey key, Func`2 valueFactory)
        at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
       at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateCode(Type[] interfaces, ProxyGenerationOptions opti
2021-05-01 16:26:06.520 2937-2995/io.sentry.samples.android I/DOTNET: ons)
        at Castle.DynamicProxy.DefaultProxyBuilder.CreateClassProxyType(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
       at Castle.DynamicProxy.ProxyGenerator.CreateClassProxyType(Type classToProxy, Type[] additiona
2021-05-01 16:26:06.520 2937-2995/io.sentry.samples.android I/DOTNET: lInterfacesToProxy, ProxyGenerationOptions options)
        at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
2021-05-01 16:26:06.520 2937-2995/io.sentry.samples.android I/DOTNET:    at NSubstitute.Proxies.CastleDynamicProxy.CastleDynamicProxyFactory.CreateProxyUsingCastleProxyGenerator(Type typeToProxy, Type[] additionalInterfaces, Object[] constructorArguments, IInterceptor[] interceptors, ProxyGenerationOptions proxyGenerationOp
2021-05-01 16:26:06.520 2937-2995/io.sentry.samples.android I/DOTNET: tions)
        at NSubstitute.Proxies.CastleDynamicProxy.CastleDynamicProxyFactory.GenerateTypeProxy(ICallRouter callRouter, Type typeToProxy, Type[] additionalInterfaces, Object[] constructorArguments)
       at NSubstitute.Proxies.CastleDynamicProxy.CastleDynamic
2021-05-01 16:26:06.521 2937-2995/io.sentry.samples.android I/DOTNET: ProxyFactory.GenerateProxy(ICallRouter callRouter, Type typeToProxy, Type[] additionalInterfaces, Object[] constructorArguments)
        at NSubstitute.Core.SubstituteFactory.Create(Type[] typesToProxy, Object[] constructorArguments, Boolean callBaseByDefault)
2021-05-01 16:26:06.521 2937-2995/io.sentry.samples.android I/DOTNET:     at NSubstitute.Core.SubstituteFactory.Create(Type[] typesToProxy, Object[] constructorArguments)
        at NSubstitute.Substitute.For(Type[] typesToProxy, Object[] constructorArguments)
       at NSubstitute.Substitute.For[IHub,IDisposable](Object[] constructor
2021-05-01 16:26:06.521 2937-2995/io.sentry.samples.android I/DOTNET: Arguments)
        at Sentry.Tests.TaskUnobservedTaskExceptionIntegrationTests.Fixture..ctor()
        at Sentry.Tests.TaskUnobservedTaskExceptionIntegrationTests..ctor()
       at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, 
2021-05-01 16:26:06.521 2937-2995/io.sentry.samples.android I/DOTNET: Boolean wrapExceptions)
       Execution time: 0
2021-05-01 16:26:06.527 2937-2995/io.sentry.samples.android I/Sentry.Android.Tests: Test completed
```

### CODE REVIEW

**Comment by bruno-garcia** [comment]
Example runner from dotnet/runtime:

https://github.com/dotnet/runtime/blob/main/src/libraries/Common/tests/AndroidTestRunner/AndroidTestRunner.cs

More on Discord: https://discord.com/channels/732297728826277939/732297837953679412/838770522070188133

**Comment by bruno-garcia** [comment]
To be clear; this will never be merged. But as we get Android support into the SDK, this has info useful to getting some tests running there.

**Comment by SimonCropp** [comment]
consider using https://github.com/dotnet/xharness

**Comment by vaind** [comment]
Note: I've pushed an incomplete (with some conflicts) merge of main into this branch, to see the changes against the current repo state

**Pull request closed without merging**
