### PR TITLE
feat: profiling low overhead

### PR DESCRIPTION
**Pull request by bruno-garcia**
#skip-changelog

### CODE REVIEW

**Comment by bruno-garcia** [comment]
@vaind got to build, but profiling tests are not running in CI 😅

**Comment by vaind** [comment]
> @vaind got to build, but profiling tests are not running in CI 😅

GJ, anything I should look into or not just yet?

**Comment by bruno-garcia** [comment]
> > @vaind got to build, but profiling tests are not running in CI 😅
> 
> GJ, anything I should look into or not just yet?

I'm looking into the whole sln/slnf stuff. I have a whole week to play with this too because of hackweek :) Thank you!

**Comment by bruno-garcia** [comment]
self TODO: 

try Environment.ProcessId instead of Process.GetCurrent

**Comment by bruno-garcia** [comment]
> I've squashed the relevant bits from this PR back into #2385 and we're adding the submodule without compiling it directly - using a project reference instead

Cool! I'll close this

**Pull request closed without merging**
