### PR TITLE
SentryTarget - GetTagsFromLogEvent with null check

### PR DESCRIPTION
**Pull request by snakefoot**
Same as #323 but for Tags

### CODE REVIEW

**Comment by bruno-garcia** [comment]
@snakefoot Thanks for raising this.
Do you mind adding a test that uses a `null` tag before we merge this?

**Comment by snakefoot** [comment]
Why me? The other PR was merged without a test :)


Sent from my Sony Xperia


---- Bruno Garcia wrote ----


@snakefoot<https://github.com/snakefoot> Thanks for raising this.
Do you mind adding a test that uses a null tag before we merge this?

**Comment by bruno-garcia** [comment]
The other PR was a simple null propagation.
You've also changed not only the null check but also 
`                 var breadcrumbFormatted = RenderLogEvent(BreadcrumbLayout, logEvent); `

And tbh I have no idea what that does.
Ideally we'd test the scenarios we're fixing, including the null checks.

**Comment by snakefoot** [comment]
> `var breadcrumbFormatted = RenderLogEvent(BreadcrumbLayout, logEvent);`

Is just an optimization, that allows NLog to make special buffer-reuse optimizations (if possible),

**Comment by snakefoot** [comment]
Sorry about using your build-server as compiler. But your solution fails to load in VS2019-Vanilla.

**Comment by snakefoot** [comment]
Yeah build succeeded :)

**Comment by bruno-garcia** [comment]
@snakefoot oh, can you please share the error?
It should load fine. I'm working on a mac though so I use Rider and just the `./build.sh` script.

So yeah you can use `powershell ./build.ps1`

**Comment by snakefoot** [comment]
```
Sentry.csproj : error  : The project file cannot be opened by the project system, because it is missing some critical imports or the referenced SDK cannot be found.

Detailed Information:
Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version.
```

**Comment by bruno-garcia** [comment]
Do you have [3.1.100 installed?](https://github.com/getsentry/sentry-dotnet/blob/159d67634bd65377e43f449c0e9682a8d50e937d/global.json#L3)

Does it build with the script?

**Comment by snakefoot** [comment]
Apparently not installed NetCore31:

```
A compatible installed .NET Core SDK for global.json version [3.1.100] from [C:\Users\snakefoot\Source\Repos\sentry-dotnet\global.json] was not found
Install the [3.1.100] .NET Core SDK or update [C:\Users\snakefoot\Source\Repos\sentry-dotnet\global.json] with an installed .NET Core SDK:
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
```

**Comment by bruno-garcia** [comment]
Latest and greatest, worth getting :)

**Pull request merged**
