### PR TITLE
Fix missing stack trace on UnobservedTaskException

### LINKED ISSUE #2065: UnobservedTaskExceptionIntegration could provide a stack trace (but doesn't)
### Package

Sentry.AspNetCore

### .NET Flavor

.NET

### .NET Version

6.0.11

### OS

Windows

### SDK Version

3.24.0

### Self-Hosted Sentry Version

_No response_

### Steps to Reproduce

1. Cause an UnobservedTaskException in a Blazor event handler, e.g.:
```
protected void CauseUnobservedTaskException()
	{
		// Task.Run(() => throw new ArgumentException("Test unobserved task exception from Blazor poke page"));
		var task = Task.Factory.StartNew(() =>
		{
			Thread.Sleep(1000); // emulate some calculation
			throw new Exception("Test unobserved task exception from Blazor poke page");
		});

			Thread.Sleep(2000); // emulate some calculation
		task = null;
		GC.Collect();
		GC.WaitForPendingFinalizers();
		GC.Collect();
	}
```
2. Allow Sentry's default handling to report the error

### Expected Result

Issue in Sentry should have a useful stack trace to the cause of the error

### Actual Result

Issue in Sentry doesn't have a stack trace.

If I turn off Sentry's handling, e.g.:
```
webBuilder.UseSentry(sentryOptions =>
{
   sentryOptions.Dsn = ...;
   sentryOptions.DisableUnobservedTaskExceptionCapture();
});
```
... and add my own code like this:
```
TaskScheduler.UnobservedTaskException += (sender, e) =>
{
	// Report the inner exception, to get the stack trace
	SentrySdk.CaptureException(e.Exception.InnerException);
};
```
... then I get a stack trace in Sentry. Could the built-in UnobservedTaskException do this, or something else clever to report the stack trace? Otherwise it's really difficult to debug these issues.

### PR DESCRIPTION
**Pull request by mattjohnsonpint**
Fixes #2065

### CODE REVIEW

**Review by bruno-garcia — APPROVED** [review]

**Comment by christallire** [comment]
Could we get this released ASAP? I have too many UnobservedTaskException without stack traces

**Comment by mattjohnsonpint** [comment]
Yes, there will be a release very soon.  Thanks for your patience.

**Comment by mattjohnsonpint** [comment]
@christallire - 3.24.1 has been release which includes this fix.  Please update and let us know how it goes.  Thanks.

**Comment by brnbs** [comment]
@mattjohnsonpint I am not sure if it's related, but I am using Sentry.AspNetCore 3.29.1 nuget and all the issues I get via UnobservedTaskException mechanism have a very short stack trace:
```
OpenQA.Selenium.WebDriverException: Cannot start the driver service on http://localhost:61414/
  ?, in void DriverService.Start()
  File "Task.cs", line 2381, in void Task.ExecuteWithThreadLocal(ref Task currentTaskSlot, Thread threadPoolThread)
```
```
System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request.
  File "Socket.Tasks.cs", line 1451, in void AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
  File "ValueTask.cs", line 271, in void ValueTaskSourceAsTask.s_completionAction(object state)
```
Is there any way to fix this?

**Comment by mattjohnsonpint** [comment]
@brnbs - That's not related to this.

You appear to have a legitimate unobserved task exception related to Selenium web driver not being able to start the driver service.  That particular exception is thrown [from here](https://github.com/SeleniumHQ/selenium/blob/43318cb969347d90007f4cbc0827a8de8a8ac937/dotnet/src/webdriver/DriverService.cs#L299-L300).

As to why it's unobserved, I can't exactly say.  At first glance doesn't appear to be in an async code path.  Given the short stack trace, I can only guess that something like `Task.Run(() => SomeDriverService.Start())` is being called somewhere.

At any rate, I don't believe there's any Sentry issue here.  Thanks.

**Pull request merged**
