### PR TITLE
chore: update DeviceTests to net8

### PR DESCRIPTION
**Pull request by vaind**
<details>
<summary>This original exception seems resolved now...</summary>

Many tests currently fail with the following exception:
```
System.InvalidCastException : Specified cast is not valid.
   at Castle.DynamicProxy.Internal.AttributeUtil.ReadAttributeValue(CustomAttributeTypedArgument argument)
   at Castle.DynamicProxy.Internal.AttributeUtil.GetArguments(IList`1 constructorArguments, Type[]& constructorArgTypes, Object[]& constructorArgs)
   at Castle.DynamicProxy.Internal.AttributeUtil.CreateInfo(CustomAttributeData attribute)
   at Castle.DynamicProxy.Internal.AttributeUtil.GetNonInheritableAttributes(ParameterInfo parameter)+MoveNext()
   at Castle.DynamicProxy.Generators.Emitters.MethodEmitter.DefineParameters(ParameterInfo[] parameters)
   at Castle.DynamicProxy.Generators.Emitters.MethodEmitter..ctor(AbstractTypeEmitter owner, String name, MethodAttributes attributes, MethodInfo methodToUseAsATemplate)
   at Castle.DynamicProxy.Generators.Emitters.AbstractTypeEmitter.CreateMethod(String name, MethodAttributes attributes, MethodInfo methodToUseAsATemplate)
   at Castle.DynamicProxy.Generators.MethodGenerator.Generate(ClassEmitter class, INamingScope namingScope)
   at Castle.DynamicProxy.Contributors.CompositeTypeContributor.ImplementMethod(MetaMethod method, ClassEmitter class, OverrideMethodDelegate overrideMethod)
   at Castle.DynamicProxy.Contributors.CompositeTypeContributor.Generate(ClassEmitter class)
   at Castle.DynamicProxy.Generators.BaseClassProxyGenerator.GenerateType(String name, INamingScope namingScope)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.<>c__DisplayClass13_0.<GetProxyType>b__0(CacheKey cacheKey)
   at Castle.Core.Internal.SynchronizedDictionary`2[[Castle.DynamicProxy.Generators.CacheKey, Castle.Core, Version=5.0.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc],[System.Type, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(CacheKey key, Func`2 valueFactory)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.GetProxyType()
   at Castle.DynamicProxy.DefaultProxyBuilder.CreateClassProxyType(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxyType(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
   at NSubstitute.Proxies.CastleDynamicProxy.CastleDynamicProxyFactory.CreateProxyUsingCastleProxyGenerator(Type typeToProxy, Type[] additionalInterfaces, Object[] constructorArguments, IInterceptor[] interceptors, ProxyGenerationOptions proxyGenerationOptions)
   at NSubstitute.Proxies.CastleDynamicProxy.CastleDynamicProxyFactory.GenerateTypeProxy(ICallRouter callRouter, Type typeToProxy, Type[] additionalInterfaces, Object[] constructorArguments)
   at NSubstitute.Proxies.CastleDynamicProxy.CastleDynamicProxyFactory.GenerateProxy(ICallRouter callRouter, Type typeToProxy, Type[] additionalInterfaces, Object[] constructorArguments)
   at NSubstitute.Core.SubstituteFactory.Create(Type[] typesToProxy, Object[] constructorArguments, Boolean callBaseByDefault)
   at NSubstitute.Core.SubstituteFactory.Create(Type[] typesToProxy, Object[] constructorArguments)
   at NSubstitute.Substitute.For(Type[] typesToProxy, Object[] constructorArguments)
   at NSubstitute.Substitute.For[IHub](Object[] constructorArguments)
   at Sentry.Tests.SentryHttpFailedRequestHandlerTests..ctor()
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

Which looks very similar to https://github.com/dotnet/runtime/issues/93770 and that should be fixed by https://github.com/dotnet/runtime/pull/94469 so I think we need to wait till that makes it to a release.

</details>

but there's a new one, which is weird because we have exactly that setting: https://github.com/getsentry/sentry-dotnet/blob/7108689f09addc2f678cb44ea0ead6bb7fa1c1af/Directory.Build.props#L100

```
        <failure exception-type="System.ArgumentException">
          <message><![CDATA[System.ArgumentException : Can not create proxy for type Sentry.Internal.IAppDomain because it is not accessible. Make it public, or internal and mark your assembly with [assembly: InternalsVisibleTo(\"DynamicProxyGenAssembly2, PublicKey=0024000004800000940000000602000000240000525341310004000001000100c547cac37abd99c8db225ef2f6c8a3602f3b3606cc9891605d02baa56104f4cfc0734aa39b93bf7852f7d9266654753cc297e7d2edfe0bac1cdcf9f717241550e0a7b191195b7667bb4f64bcb8e2121380fd1d9d46ad2d92d2d15605093924cceaf74c4861eff62abf69b9291ed0a340e113be11e6a7d3113e92484cf7045cc7\")] attribute, because assembly Sentry is strong-named. Arg_ParamName_Name, additionalInterfacesToProxy]]></message>
          <stack-trace><![CDATA[   at Castle.DynamicProxy.DefaultProxyBuilder.AssertValidTypeForTarget(Type type, Type target, String paramName)
   at Castle.DynamicProxy.DefaultProxyBuilder.AssertValidType(Type target, String paramName)
   at Castle.DynamicProxy.DefaultProxyBuilder.AssertValidTypes(IEnumerable`1 targetTypes, String paramName)
   at Castle.DynamicProxy.DefaultProxyBuilder.CreateClassProxyType(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxyType(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
   at NSubstitute.Proxies.CastleDynamicProxy.CastleDynamicProxyFactory.CreateProxyUsingCastleProxyGenerator(Type typeToProxy, Type[] additionalInterfaces, Object[] constructorArguments, IInterceptor[] interceptors, ProxyGenerationOptions proxyGenerationOptions)
   at NSubstitute.Proxies.CastleDynamicProxy.CastleDynamicProxyFactory.GenerateTypeProxy(ICallRouter callRouter, Type typeToProxy, Type[] additionalInterfaces, Object[] constructorArguments)
   at NSubstitute.Proxies.CastleDynamicProxy.CastleDynamicProxyFactory.GenerateProxy(ICallRouter callRouter, Type typeToProxy, Type[] additionalInterfaces, Object[] constructorArguments)
   at NSubstitute.Core.SubstituteFactory.Create(Type[] typesToProxy, Object[] constructorArguments, Boolean callBaseByDefault)
   at NSubstitute.Core.SubstituteFactory.Create(Type[] typesToProxy, Object[] constructorArguments)
   at NSubstitute.Substitute.For(Type[] typesToProxy, Object[] constructorArguments)
   at NSubstitute.Substitute.For[IAppDomain](Object[] constructorArguments)
   at Sentry.Tests.UnobservedTaskExceptionIntegrationTests.Fixture..ctor()
   at Sentry.Tests.UnobservedTaskExceptionIntegrationTests..ctor()
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object , BindingFlags )]]></stack-trace>
        </failure>

#skip-changelog

### CODE REVIEW

**Comment by bitsandfoxes** [comment]
Superseded by https://github.com/getsentry/sentry-dotnet/pull/3286

**Comment by bitsandfoxes** [comment]
Derp.. jumped the gun

**Comment by bruno-garcia** [comment]
I wonder if there's a chance we get this to work at this point? I'm concerned it might get super stale eventually

**Comment by jamescrosswell** [comment]
@vaind I managed to get this going in [the net9.0 branch](https://github.com/getsentry/sentry-dotnet/pull/3699).

There were multiple things going on:
- When targeting net8.0-android, [trimming has to be disabled](https://github.com/getsentry/sentry-dotnet/blob/ec2335e5d34a7c6e93e991e0bc02d273dcc777bc/scripts/device-test.ps1#L62-L63) (we had it enabled implicitly with the `IsAotCompatible` build property)
- To get the iOS device tests running locally on my mac, an [x64 runtime identifier had to be used](https://github.com/getsentry/sentry-dotnet/blob/196d00d73e46b7a93ef9b9b901cf9a9192c6cab6/test/Sentry.Maui.Device.TestApp/Sentry.Maui.Device.TestApp.csproj#L59-L60)
- To get the iOS device tests to run against net8.0-ios, [the interpreter has to be enabled explicitly](https://github.com/getsentry/sentry-dotnet/blob/196d00d73e46b7a93ef9b9b901cf9a9192c6cab6/test/Sentry.Maui.Device.TestApp/Sentry.Maui.Device.TestApp.csproj#L42-L45) (presumably the default for this was changed between net7.0-ios and net8.0-ios

I'll close this PR then.

**Comment by vaind** [comment]
> @vaind I managed to get this going in [the net9.0 branch](https://github.com/getsentry/sentry-dotnet/pull/3699).

thanks, much appreciated!

**Pull request closed without merging**
