### PR TITLE
Move tunnel functionality into  into Sentry.AspNetCore

### LINKED ISSUE #1141: Improvements for `Sentry.Tunnel`
- [ ] Split AddSentryTunnel and UseSentryTunnel into different files and use already imported namespace (like `Microsoft.AspNetCore.Builder`. See Sentry.AspNetCore)
- [ ] Documentation must mention the need for registering HttpClientFactory (`[18:18:21 ERR] Connection id "0HMAFN6VRLADL", Request id "0HMAFN6VRLADL:00000006": An unhandled exception was thrown by the application.
System.InvalidOperationException: No service for type 'System.Net.Http.IHttpClientFactory' has been registered.`
- [ ] Document to include it either before/after the tracing middleware.
- [ ] Add the middleware docs to the actually Sentry docs: [docs.sentry.io/platforms/javascript/guides/wasm/troubleshooting](https://docs.sentry.io/platforms/javascript/guides/wasm/troubleshooting/)
- [ ] Add the tunnel to the ASP.NET Core sample and use it from the error page which has User Feedback (that has JS SDK)

### PR DESCRIPTION
**Pull request by SimonCropp**
* Copies `SentryTunnelMiddleware` into `Sentry.AspNetCore`
 * Adds a nuget dependency from `Sentry.Tunnel` to `Sentry.AspNetCore`
 * Stubs out the old `Sentry.Tunnel.SentryTunnelMiddleware` by inheriting from `Sentry.AspNetCore.SentryTunnelMiddleware`
 * Obsoletes `Sentry.Tunnel.SentryTunnelMiddleware`
 * Merges `Sentry.Tunnel.Tests` into `Sentry.AspNetCore.Tests`
 * Removes `[Collection("SentryTunnelCollection")]` from `IntegrationsTests`
 * Copies extension methods from `SentryTunnelingApplicationBuilderExtensions` into `SentryWebHostBuilderExtensions`
 * Redirects method in `SentryTunnelingApplicationBuilderExtensions` to `SentryWebHostBuilderExtensions`
 * Obsoletes `SentryTunnelingApplicationBuilderExtensions` and points to `SentryWebHostBuilderExtensions`
 * Obsolete `Sentry.Tunnel` on nuget.

fixes #1141

### CODE REVIEW

**Comment by SimonCropp** [comment]
Questions

 * @bruno-garcia what did `[Collection("SentryTunnelCollection")]` do?
 * If we want the tunnel host build API, i will need help. I failed to reverse engineer that code
 * Why is SentryTunnelMiddleware public?

**Comment by mattjohnsonpint** [comment]
> * @mattjohnsonpint i thought you already updated the docs related to tunneling?

nope

**Comment by bruno-garcia** [comment]
We can add the NuGet package obsolete on the gallery once we ship this.

**Comment by SimonCropp** [comment]
@mattjohnsonpint @bruno-garcia one complexity of this is for people using `Sentry.AspNet` (non core). shouldnt they using tunnel as well?

**Review by mattjohnsonpint — APPROVED** [review]

**Comment by mattjohnsonpint** [comment]
Tunneling is useful, but completely optional.  We didn't have a ASP.NET (non-core) tunnel before, so it's not an issue at the moment.  If it becomes higher priority, we could consider adding one to `Sentry.AspNet` later.

**Pull request merged**
