### PR TITLE
Add missing packages to craft file

### PR DESCRIPTION
**Pull request by jamescrosswell**
#skip-changelog

Added `Sentry.AzureFunctions.Worker` and `Sentry.OpenTelemetry` to `.craft.yml` so that these get included in the [release registry](https://github.com/getsentry/craft#sentry-release-registry-registry).

### CODE REVIEW

**Review by bruno-garcia — CHANGES_REQUESTED** [review]
Before merging this we need to add these to https://github.com/getsentry/sentry-release-registry/ which requires 1 of a few ppl at Sentry with perm to merge so blocking for now

**Comment by bruno-garcia** [comment]
prob best to take this chance and rename AzureFunctions to Azure.Functions and GA it, wdty

**Comment by bitsandfoxes** [comment]
Let's fix https://github.com/getsentry/sentry-dotnet/issues/2579 and GA this.

**Review by bruno-garcia — COMMENTED** [review]
to leave it unblocked

**Comment by bruno-garcia** [comment]
image
needs an approval now to let this get merged 🙄

**Review by bitsandfoxes — APPROVED** [review]

**Review by bitsandfoxes — CHANGES_REQUESTED** [review]
We're not! Sec

**Review by bitsandfoxes — APPROVED** [review]

**Pull request merged**
